apiVersion: v1
kind: Namespace
metadata:
  name: talentsphere-staging
  labels:
    name: talentsphere-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: talentsphere-production
  labels:
    name: talentsphere-production
    environment: production